# Generated by Django 2.1.1 on 2018-10-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('para1', models.CharField(max_length=200)),
                ('para2', models.CharField(max_length=200)),
                ('para3', models.CharField(max_length=200)),
                ('para4', models.CharField(max_length=200)),
                ('para5', models.CharField(max_length=200)),
                ('para6', models.CharField(max_length=200)),
            ],
        ),
    ]
