# Generated by Django 2.1.1 on 2018-10-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0003_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='miner.Miner')),
                ('pool', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='miner.Pool')),
            ],
        ),
    ]
