# Generated by Django 2.1.1 on 2018-10-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0004_poolmux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolmux',
            old_name='owner',
            new_name='miner',
        ),
    ]
